### ISSUE TITLE
schematic opto-couplers

### ISSUE THREAD

**Issue by slug** [jaroslawprzybylowicz/fuji-iot#14]
Hi, thank you for this project. In the project description (README) you mention opto-couplers for the rx/tx comm lines, but looking at your schematic I don't see those being used. Is there a newer version of it?

**Comment by jaroslawprzybylowicz** [comment]
Hi. This is error in the description. My original project had those optocouplers (and external power source). Here however RPi and optocouplers would be effectively powered from the same SMPS, so introducing octo-couplers doesn't provide much of a benefit.
