### ISSUE TITLE
How to use it with ESP8266 or ESP32?

### ISSUE THREAD

**Issue by marciogranzotto** [jaroslawprzybylowicz/fuji-iot#17]
I'm interested in using this, but I have 6 AC units that I need to automate.
Can you give me directions on which parts of the software I need to create a ESP version?

**Comment by jaroslawprzybylowicz** [comment]
The biggest obstacle is likely the build system (Bazel) as it does not support ESP32. I'd recommend to just drop bazel in that case and compile with whatever toolchain for ESP32 you have.

As for the code itself it is layered into two pieces.
- fuji-iot/protocol/* - this is the secret sauce, it contains all the logic needed to operate the AC. It has dependency on abseil-cpp, which might be difficult to port. At the same time uses it only in a couple of places, so if port is not possible you can likely work that around with a little effort.
- fuji-iot/controller/* - this directory contains interfacing logic. fuji_ac_server.cc and fuji_ac_controller.proto define gRPC service - I'm not sure what kind of interface you want to expose to the world, but depending on that you might want to keep it or throw away. Once you decide that, FujiAcController will likely need some tweaks, you also need to implement your own FujiAcSerialInterface as it's implementation in fuji_ac_serial_reader.cc is POSIX targeted.

**Comment by unreality** [comment]
@marciogranzotto, i've created an Arduino library based on @jaroslawprzybylowicz's work at https://github.com/unreality/FujiHeatPump if interested

**Comment by jaroslawprzybylowicz** [comment]
That library is neat! 
I've added some notes in the documentation to point to the Arduino implementation.
